# Generated by Django 5.2.11 on 2026-02-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StgAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_id', models.CharField(max_length=50)),
                ('addr_line1', models.CharField(blank=True, max_length=200, null=True)),
                ('addr_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('flat', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['bp_id'], name='ingestion_s_bp_id_b4e6c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='StgCustomerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_id', models.CharField(max_length=50)),
                ('bp_creation_date', models.DateField(blank=True, null=True)),
                ('bp_creation_source', models.CharField(blank=True, max_length=50, null=True)),
                ('bp_number', models.CharField(blank=True, max_length=50, null=True)),
                ('id_type', models.CharField(blank=True, max_length=50, null=True)),
                ('id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('contract_account', models.CharField(blank=True, max_length=50, null=True)),
                ('contract', models.CharField(blank=True, max_length=50, null=True)),
                ('installation', models.CharField(blank=True, max_length=50, null=True)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('extra_attributes', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['id_type', 'id_number'], name='ingestion_s_id_type_1ccb47_idx'), models.Index(fields=['bp_id'], name='ingestion_s_bp_id_683716_idx')],
            },
        ),
        migrations.CreateModel(
            name='StgFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_id', models.CharField(max_length=50)),
                ('contract_account', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'indexes': [models.Index(fields=['bp_id'], name='ingestion_s_bp_id_bf615f_idx'), models.Index(fields=['contract_account'], name='ingestion_s_contrac_592d9b_idx')],
            },
        ),
    ]
