# Generated by Django 5.2.11 on 2026-02-26 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dedupe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retained_bp', models.CharField(max_length=50)),
                ('bp_to_merge', models.CharField(max_length=50)),
                ('proposed_new_ca', models.CharField(blank=True, max_length=50, null=True)),
                ('actions_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='Draft', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dedupe.dupgroup')),
            ],
        ),
    ]
