# Generated by Django 5.2.11 on 2026-03-15 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushCleansedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dup_member_id', models.IntegerField()),
                ('retained_bp', models.CharField(max_length=50)),
                ('retained_account', models.CharField(blank=True, max_length=50, null=True)),
                ('payload_json', models.JSONField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('PUSHED', 'Pushed'), ('ERROR', 'Error')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
