# Generated by Django 5.2.11 on 2026-03-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupe', '0002_pushcleanseddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushcleanseddata',
            name='push_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pushcleanseddata',
            name='pushed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pushcleanseddata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
