# Generated by Django 5.2.11 on 2026-03-17 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupe', '0003_pushcleanseddata_push_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dupmember',
            name='account_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dupmember',
            name='contract',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dupmember',
            name='contract_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dupmember',
            name='installation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='dedupe.dupgroup'),
        ),
        migrations.AlterField(
            model_name='pushcleanseddata',
            name='payload_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
