# Generated by Django 5.2.11 on 2026-03-17 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupe', '0004_dupmember_account_class_dupmember_contract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushcleanseddata',
            name='dup_member_id',
        ),
        migrations.AddField(
            model_name='pushcleanseddata',
            name='dup_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dedupe.dupgroup'),
        ),
        migrations.AddField(
            model_name='pushcleanseddata',
            name='dup_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dedupe.dupmember'),
        ),
    ]
