# Generated by Django 5.2.11 on 2026-03-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedupe', '0005_remove_pushcleanseddata_dup_member_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushcleanseddata',
            name='retained_bp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
