{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "22f643c6",
   "metadata": {},
   "outputs": [],
   "source": [
    "import csv\n",
    "from pathlib import Path\n",
    "from django.core.management.base import BaseCommand\n",
    "from ingestion.models import StgCustomerMaster, StgFinancial, StgAddress\n",
    "from datetime import datetime\n",
    "import json\n",
    "\n",
    "def parse_date(s):\n",
    "    s = (s or \"\").strip()\n",
    "    if not s:\n",
    "        return None\n",
    "    return datetime.strptime(s, \"%Y-%m-%d\").date()\n",
    "\n",
    "class Command(BaseCommand):\n",
    "    help = \"Load staging tables from CSVs (customer_master, financial, address).\"\n",
    "\n",
    "    def add_arguments(self, parser):\n",
    "        parser.add_argument(\"--dir\", type=str, required=True, help=\"Folder containing CSVs\")\n",
    "\n",
    "    def handle(self, *args, **opts):\n",
    "        data_dir = Path(opts[\"dir\"])\n",
    "\n",
    "        cust_csv = data_dir / \"customer_master.csv\"\n",
    "        fin_csv  = data_dir / \"financial.csv\"\n",
    "        addr_csv = data_dir / \"address.csv\"\n",
    "\n",
    "        # Clear old (MVP)\n",
    "        StgCustomerMaster.objects.all().delete()\n",
    "        StgFinancial.objects.all().delete()\n",
    "        StgAddress.objects.all().delete()\n",
    "\n",
    "        # Load Customer Master\n",
    "        cust_rows = []\n",
    "        with cust_csv.open(\"r\", encoding=\"utf-8\") as f:\n",
    "            reader = csv.DictReader(f)\n",
    "            for r in reader:\n",
    "                extra = (r.get(\"extra_attributes\") or \"\").strip()\n",
    "                cust_rows.append(StgCustomerMaster(\n",
    "                    bp_id=r.get(\"bp_id\",\"\").strip(),\n",
    "                    bp_creation_date=parse_date(r.get(\"bp_creation_date\")),\n",
    "                    bp_creation_source=(r.get(\"bp_creation_source\") or \"\").strip(),\n",
    "                    bp_number=(r.get(\"bp_number\") or \"\").strip(),\n",
    "\n",
    "                    id_type=(r.get(\"id_type\") or \"\").strip(),\n",
    "                    id_number=(r.get(\"id_number\") or \"\").strip(),\n",
    "\n",
    "                    email=(r.get(\"email\") or \"\").strip() or None,\n",
    "                    mobile_number=(r.get(\"mobile_number\") or \"\").strip() or None,\n",
    "                    date_of_birth=parse_date(r.get(\"date_of_birth\")),\n",
    "                    nationality=(r.get(\"nationality\") or \"\").strip() or None,\n",
    "                    gender=(r.get(\"gender\") or \"\").strip() or None,\n",
    "\n",
    "                    contract_account=(r.get(\"contract_account\") or \"\").strip(),\n",
    "                    contract=(r.get(\"contract\") or \"\").strip(),\n",
    "                    installation=(r.get(\"installation\") or \"\").strip(),\n",
    "                    move_in_date=parse_date(r.get(\"move_in_date\")),\n",
    "                    move_out_date=parse_date(r.get(\"move_out_date\")),\n",
    "\n",
    "                    extra_attributes=json.loads(extra) if extra else None\n",
    "                ))\n",
    "        StgCustomerMaster.objects.bulk_create(cust_rows, batch_size=1000)\n",
    "        self.stdout.write(self.style.SUCCESS(f\"✅ Loaded customer master: {len(cust_rows)}\"))\n",
    "\n",
    "        # Load Financial\n",
    "        fin_rows = []\n",
    "        with fin_csv.open(\"r\", encoding=\"utf-8\") as f:\n",
    "            reader = csv.DictReader(f)\n",
    "            for r in reader:\n",
    "                fin_rows.append(StgFinancial(\n",
    "                    bp_id=r.get(\"bp_id\",\"\").strip(),\n",
    "                    contract_account=(r.get(\"contract_account\") or \"\").strip(),\n",
    "                    payment_date=parse_date(r.get(\"payment_date\")),\n",
    "                    payment_amount=r.get(\"payment_amount\") or 0\n",
    "                ))\n",
    "        StgFinancial.objects.bulk_create(fin_rows, batch_size=2000)\n",
    "        self.stdout.write(self.style.SUCCESS(f\"✅ Loaded financial: {len(fin_rows)}\"))\n",
    "\n",
    "        # Load Address\n",
    "        addr_rows = []\n",
    "        with addr_csv.open(\"r\", encoding=\"utf-8\") as f:\n",
    "            reader = csv.DictReader(f)\n",
    "            for r in reader:\n",
    "                addr_rows.append(StgAddress(\n",
    "                    bp_id=r.get(\"bp_id\",\"\").strip(),\n",
    "                    addr_line1=(r.get(\"addr_line1\") or \"\").strip(),\n",
    "                    addr_line2=(r.get(\"addr_line2\") or \"\").strip(),\n",
    "                    building=(r.get(\"building\") or \"\").strip(),\n",
    "                    flat=(r.get(\"flat\") or \"\").strip(),\n",
    "                    street=(r.get(\"street\") or \"\").strip(),\n",
    "                    area=(r.get(\"area\") or \"\").strip(),\n",
    "                    city=(r.get(\"city\") or \"\").strip(),\n",
    "                    postal_code=(r.get(\"postal_code\") or \"\").strip(),\n",
    "                    country=(r.get(\"country\") or \"\").strip(),\n",
    "                ))\n",
    "        StgAddress.objects.bulk_create(addr_rows, batch_size=1000)\n",
    "        self.stdout.write(self.style.SUCCESS(f\"✅ Loaded address: {len(addr_rows)}\"))\n",
    "\n",
    "        self.stdout.write(self.style.SUCCESS(\"🎉 Staging load complete.\"))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
